/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Mar 19 17:38:20 KST 2020
 */

package org.apache.commons.pool2;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class PooledObject_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.pool2.PooledObject"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PooledObject_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.pool2.impl.ThrowableCallStack",
      "org.apache.commons.pool2.impl.SecurityManagerCallStack",
      "org.apache.commons.pool2.impl.SecurityManagerCallStack$PrivateSecurityManager",
      "org.apache.commons.pool2.impl.PooledSoftReference",
      "org.apache.commons.pool2.impl.ThrowableCallStack$Snapshot",
      "org.apache.commons.pool2.impl.NoOpCallStack",
      "org.apache.commons.pool2.PooledObject",
      "org.apache.commons.pool2.impl.CallStack",
      "org.apache.commons.pool2.impl.CallStackUtils",
      "org.apache.commons.pool2.TrackedUse",
      "org.apache.commons.pool2.impl.DefaultPooledObject",
      "org.apache.commons.pool2.PooledObjectState"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.commons.pool2.PooledObject", false, PooledObject_ESTest_scaffolding.class.getClassLoader()));
  }
}
