/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 17:40:41 KST 2020
 */

package org.apache.commons.pool2;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PooledObjectFactory_ESTest extends PooledObjectFactory_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
